<?php
/*
 * *** DO NOT EDIT THIS FILE!!! ***
 * Any changes made in this file will be lost on future upgrades.  Any of these
 * values which are specified in the configure.php.local file will override
 * those contained in this file.
*/
// Sets the default timezone:
date_default_timezone_set('GMT');

// Sets the email header information for email that is generated as part of this
// system.
$emailFromAddress = "example@example.com";
$emailReplyToAddress = "example@example.com";
$emailSignatureText = "Fill in your text here";

// Sets the default maximum number of days the event reminder program will use
// to search for events.  This should be greater than or equal to the longest
// reminder period that is set in the reminders table.
$maxDays = 7;

// Sets the variance in time stamp checking for reminders in seconds.  The larger the
// variance the greater the more tolerant the reminder checking is.  It can be taken
// too far which will cause sending duplicate reminders.
$timeStampVariance = 10;

// REMOVE THE FOLLOWING LINES FROM THE configure.php.local file:
include 'configure.php.local';
?>
